---
kind: pipeline
name: preview

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:18-alpine
    commands:
      - yarn install --frozen-lockfile
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: ignore-openapi
    image: node:18-alpine
    commands:
      - apk update && apk add git
      - ./scripts/ignore-openapi
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build
    image: node:18-alpine
    commands:
      - NODE_OPTIONS="--max-old-space-size=8192" yarn build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: package
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get -y install zip
      - zip -q -r build.zip build/
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: preview
    image: chhooo/drone-netlify:v0.1.0
    environment:
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_SITE_ID
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - pull_request

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:18-alpine
    commands:
      - yarn install --frozen-lockfile
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: ignore-openapi
    image: node:18-alpine
    commands:
      - apk update && apk add git
      - ./scripts/ignore-openapi
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: build
    image: node:18-alpine
    commands:
      - NODE_OPTIONS="--max-old-space-size=8192" yarn build
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push