---
kind: pipeline
name: preview

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:18-alpine
    commands:
      - yarn install
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: ignore-openapi # check the api/swagger.json and docs/api/*
    image: node:18-alpine
    commands:
      - apk update && apk add git
      - ./scripts/ignore-openapi
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: build
    image: node:18-alpine
    commands:
      - NODE_OPTIONS="--max-old-space-size=8192" yarn build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: package
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get -y install zip
      - zip -q -r build.zip build/
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - pull_request

  - name: preview
    image: chhooo/drone-netlify:v0.1.0
    environment:
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_SITE_ID
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    when:
      event:
        - pull_request

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - pull_request

#---
#kind: pipeline
#name: release
#
#platform:
#  os: linux
#  arch: amd64
#
#steps:
#  - name: install
#    image: node:18-alpine
#    commands:
#      - yarn install --frozen-lockfile
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#
#  - name: ignore-openapi
#    image: ubuntu:latest
#    commands:
#      - ./scripts/clean-openapi
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#
#  - name: build
#    image: node:18-alpine
#    commands:
#      - NODE_OPTIONS="--max-old-space-size=8192" yarn build
#    volumes:
#      - name: docker
#        path: /var/run/docker.sock
#
#volumes:
#  - name: docker
#    host:
#      path: /var/run/docker.sock
#
#trigger:
#  branch:
#    - main