#!/bin/sh

BEFORE_COMMIT_ID=${DRONE_COMMIT_BEFORE}
AFTER_COMMIT_ID=${DRONE_COMMIT}

FILES=$(git --no-pager diff --name-only ${BEFORE_COMMIT_ID}...${AFTER_COMMIT_ID})
echo 1
# 判断/api/swaggers.json文件变更
if echo "$FILES" | grep -q "api/swagger.json"; then
    # 执行yarn generate并检查是否有dirty文件
    yarn clean-api-docs all
    yarn gen-api-docs all
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        echo "Error: Found dirty files. Please resolve the issues before continuing."
        exit 1
    fi
    exit 0
fi

# 判断/docs/api目录下的文件变更
if echo "$FILES" | grep -q "docs/api/"; then
    exit 0
fi

rm -rf docs/api/*.mdx
cat << EOF > docs/api/sidebar.js
module.exports = [];
EOF